.fixtures.yml, .fixtures.yml.local, .travis.yml, Gemfile
SIMP-170 #close Update sssd for travis
=> (SIMP-170) Update pupmod-simp-sssd for travis

manifests/init.pp
Updated the services list for SSSD to cover SSH and Sudo.
SIMP-612 #comment Update to enable SSH and Sudo support
=> (SIMP-612) Added SSH and Sudo to the servies

.fixtures.yml, build/pupmod-sssd.spec, manifests/init.pp, manifests/install.pp, manifests/provider/ldap.pp, manifests/service/pam.pp, manifests/service/ssh.pp, metadata.json
Enables compliance checking support for sssd module
SIMP-720 #comment added compliance support
=> (SIMP-720) Map 800-53 requirements to hiera

build/pupmod-sssd.spec, manifests/init.pp, metadata.json
- Migrated use_simp_pki to a global catalyst.
SIMP-894 #comment Fixes for issues discovered during testing
=> (SIMP-894) Fixed issues discovered during testing

manifests/service/pam.pp
-fixed a typo
SIMP-2122 #comment just a fix do not close
=> (SIMP-2122) Fix typo in SSSd module

CHANGELOG, manifests/domain.pp, manifests/provider/krb5.pp, manifests/provider/local.pp, manifests/service/autofs.pp, manifests/service/nss.pp, manifests/service/pac.pp, manifests/service/pam.pp, manifests/service/ssh.pp, manifests/service/sudo.pp
- updated the type of the debug level variable to be consistent
for all modules and correct
SIMP-2674 #close
=> (SIMP-2674) Update type of debug level

README.md
Changes according to discussion of readme style with Kendall, Ryan, Tyler, and others. 
SIMP-2759 #close
=> (SIMP-2759) finished modifying readme

.travis.yml, CHANGELOG, metadata.json
CHANGELOG includes unrecorded changes made by others
SIMP-2871 #close
=> (SIMP-2871) Fix metadata pupmod-simp-sssd

README.md
=> (SIMP-2564) Update hiera ref to lookup()

.gitlab-ci.yml
=> (SIMP-3235) add gitlabci to simp module

.fixtures.yml, .gitlab-ci.yml, .travis.yml
SIMP-3903 #close sssd use concat 4.1.1 in tests
=> (SIMP-3903) sssd use concat 4.1.1 in tests

.fixtures.yml, .gitlab-ci.yml, CHANGELOG, manifests/provider/ad.pp, spec/acceptance/suites/ad/00_setup_ad_spec.rb, spec/acceptance/suites/ad/50_ad_spec.rb, spec/acceptance/suites/ad/files/populate_ad.ps1, spec/acceptance/suites/ad/files/sssd.conf.txt, spec/acceptance/suites/ad/nodesets/default.yml, templates/provider/ad.erb
SIMP-4454 #close
SIMP-4453 #close
=> (SIMP-4454) sssd: AD acceptance test updates

.gitlab-ci.yml, CHANGELOG, manifests/provider/ad.pp, metadata.json, spec/acceptance/suites/ad/50_ad_spec.rb, spec/acceptance/suites/ad/files/sssd.conf.txt
- sssd::provider::ad::ldap_schema should be a string, not a boolean
- AD test cleanup
SIMP-4317 #comment fix sssd::provider::ad::ldap_schema data type
=> (SIMP-4317) Fix AD test suite and ldap_schema

CHANGELOG, Gemfile, manifests/install.pp, manifests/install/client.pp, spec/acceptance/suites/ad/nodesets/default.yml, spec/acceptance/suites/ad/nodesets/oel.yml, spec/classes/install_spec.rb, spec/spec_helper_acceptance.rb
- Changed $sssd::install::package_ensure from 'latest' to 'installed'
- It will also respect `simp_options::package_ensure`
SIMP-2971 #comment update sssd
=> (SIMP-2971) Add $simp_options::package_ensure

.gitlab-ci.yml, .travis.yml, Gemfile
- Update to version of simp-beaker-helpers that doesn't try to
enble FIPS on Windows boxes
- Add GitLab job for ad suite in FIPS mode
=> (SIMP-MAINT) Test ad suite in FIPS mode

CHANGELOG, spec/acceptance/suites/ad/00_setup_ad_spec.rb, spec/acceptance/suites/ad/50_ad_spec.rb, spec/acceptance/suites/ad/files/populate_ad.ps1
=> (SIMP-6175) Fix AD Tests

.fixtures.yml, .gitlab-ci.yml
- Unpin puppet-systemd in fixtures
- Reinstate ad suite jobs in GitLab
SIMP-6949 #comment pupmod-simp-sssd
SIMP-6995 #close
=> (SIMP-6949) Fixtures pinned to wrong puppet-systemd branch

.gitlab-ci.yml, .pmtignore, .puppet-lint.rc, Gemfile.project
SIMP-8301 #close
[SIMP-7855] #comment Updated pupmod-simp-sssd
SIMP-8237 #comment Added `--no-parameter_order_check` to pupmod-simp-sssd
[SIMP-7855]: https://simp-project.atlassian.net/browse/SIMP-7855
=> (SIMP-7855) Update GLCI to test puppet 5.5.20

.fixtures.yml, .gitlab-ci.yml, CHANGELOG, metadata.json, spec/acceptance/nodesets/oel.yml, spec/acceptance/suites/ad/nodesets/default.yml, spec/acceptance/suites/ad/nodesets/oel.yml, spec/acceptance/suites/ds389/00_setup_389ds_spec.rb, spec/acceptance/suites/ds389/10_setup_clients_spec.rb, spec/acceptance/suites/ds389/nodesets/default.yml, spec/acceptance/suites/ds389/nodesets/oel.yml, spec/acceptance/suites/ds389/templates/ds389_hiera.yaml.erb, spec/acceptance/suites/ldap/nodesets/oel.yml
- Added a 389ds acceptance test.
SIMP-9742 #close
SIMP-9737 #comment sssd test complete.
=> (SIMP-9737) Add 389ds accept tests - sssd

CHANGELOG, metadata.json, templates/provider/krb5.epp
=> Match template to manifest

CHANGELOG, REFERENCE.md, manifests/init.pp, manifests/provider/ldap.pp, manifests/service/pam.pp, metadata.json, spec/classes/init_spec.rb, spec/defines/provider/ldap_spec.rb, templates/provider/ldap.erb, templates/service/pam.erb
=> (#143) Added support for smartcard params for pam and ldap

CHANGELOG, metadata.json, spec/classes/service/ifp_spec.rb, templates/service/ifp.erb
=> fix allowed_uids parameter in ifp template
