- .travis.yml
- build/pupmod-sssd.spec
- manifests/provider/ldap.pp
- metadata.json
- templates/provider/ldap.erb
The `ldap_chpass_updates_last_change` parameter was incorrect and has
been removed in place of `ldap_chpass_update_last_change`
SIMP-917 #close
> (SIMP-917) Fix bug in SSSD LDAP Provider

- .fixtures.yml
The openldap module is not requires for any sssd tests
> (SIMP-2427) Remove unnecessary dependency

- manifests/provider/ldap.pp
The plaintext bind_pw should be included in the sssd.conf file, not the
bind_hash.
SIMP-2554 #close
> (SIMP-2554) Change bind_hash to bind_pw

- CHANGELOG
- manifests/provider/ldap.pp
- spec/defines/provider/ldap_spec.rb
- templates/provider/ldap.erb
The client LDAP libraries are broken in EL6 such that, if any 128 bit
ciphers are present in the cipher string, it will fall back to SSF=128
for connecting to an LDAP server.
This is unacceptable to the SIMP default configuration (SSF=256).
Also, fixed a bug in a template with regards to variables with prefaced
underscores.
SIMP-2992 #comment Update for SSSD
> (SIMP-2992) Work around for broken LDAP libs

- CHANGELOG
- README.md
- manifests/init.pp
- metadata.json
- spec/classes/init_spec.rb
- types/debuglevel.pp
- Sssd::DebugLevel now handles all variants specfied in sssd.conf man page
- All instances of debug_level are now typed as Sssd::DebugLevel
SIMP-3016 #comment ready for testing
SIMP-3696 #close
SIMP-3690 #close
> (SIMP-3016) Update Sssd::DebugLevel type

- .travis.yml
- CHANGELOG
- manifests/init.pp
- metadata.json
- spec/classes/init_spec.rb
Prior to this commit it was possible to set the parameter `sssd::domains` to the empty array or an array containing the empty string, neither of which is allowed according to the README.  The resulting behavior in such a cases was undefined and generally erroneous.  This commit sets a minimum length on the parameter's array to 1, and requires the contained strings to be between 1 and 255 characters in accordance with RFC 2181.
SIMP-3803 #close
> (SIMP-3803) Set minimum length on sssd::domains

- CHANGELOG
- README.md
- manifests/provider/ldap.pp
- spec/defines/provider/ldap_spec.rb
This is helpful to ease adoption of this module in pre-existing systems,
without adding a dependency on simp-pki right away.
The parameter was already handled by the related template.
> Allow passing ldap_tls_cacert to sssd::provider::ldap

- CHANGELOG
- manifests/install.pp
- manifests/service.pp
- metadata.json
- spec/classes/install_spec.rb
- Avoid changing the permissions /etc/sssd from the vendored RPM
- owner is no longer managed
- perms went from 0640 to 0711
SIMP-4652 #comment sssd fixed
> (SIMP-4652) sssd: Unmangle /etc/sssd perms

- .gitlab-ci.yml
- CHANGELOG
- manifests/provider/ad.pp
- metadata.json
- spec/acceptance/suites/ad/files/sssd.conf.txt
- spec/acceptance/suites/default/files/sssd.conf.txt
- templates/provider/ad.erb
This change adds the following settings to the ad provider
- ldap_use_tokengroups
- ldap_group_objectsid
- ldap_user_objectsid
These settings are supported for SSSD as of version 1.12.4 and are required
to satisfy some lookup issues when connecting to AD.
Closes SIMP-4949
> (SIMP-4949) Add ldap values to ad provider

- .gitlab-ci.yml
- .travis.yml
- CHANGELOG
- Gemfile
- metadata.json
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/oel.yml
- spec/acceptance/suites/ad/nodesets/oel.yml
- spec/spec_helper_acceptance.rb
Add support for Puppet 5 and OEL in metadata, Gemfile updates, and
acceptance testing.
**NOTE** The acceptance tests for OEL-AD will not pass until updates are made to pupmod-simp-ssh and the merge for pupmod-simp-simp goes through.
> (SIMP-4009) Add Puppet 5 and OEL Support

- CHANGELOG
- manifests/provider/ldap.pp
- spec/defines/provider/ldap_spec.rb
Adds support for 128 bit cipher workaround that was missed for OEL previously.
SIMP-4009 #comment OEL support fixed
> (SIMP-4009) OEL Support for LDAP Provider

- spec/acceptance/nodesets/oel.yml
Updated boxes in comments, to prevent future problems
when the commented-out nodes are activated.
SIMP-5477 #comment update to onxypoint OEL box pupmod-simp-sssd
> (SIMP-5477) Update to onyxpoint OEL box

- CHANGELOG
- functions/ldap_access_order_defaults.pp
- metadata.json
- spec/defines/provider/ldap_spec.rb
- spec/functions/ldap_access_order_spec.rb
Change the sssd::provider::ldap::ldap_access_order defaults to
['ppolicy','pwd_expire_policy_renew'] by default to prevent accidental
system lockouts on upgrade.
SIMP-6152 #close
> (SIMP-6152) Change ldap_access_order to renew

- .fixtures.yml
- .gitlab-ci.yml
- Tested with concat 5.3.0 to ensure compatibility with SIMP 6.4.0
- Updated fixtures to latest and greatest (6.x currently)
- Allow spec tests to fail in GitLab.  They pass in TravisCI.  There is a separate ticket for that problem: SIMP 6932
> (SIMP-6922) concat pinned to wrong version in fixtures

- CHANGELOG
- README.md
- manifests/config.pp
- manifests/domain.pp
- manifests/init.pp
- manifests/provider/ad.pp
- manifests/provider/files.pp
- manifests/provider/ipa.pp
- manifests/provider/krb5.pp
- manifests/provider/ldap.pp
- manifests/provider/local.pp
- metadata.json
- spec/acceptance/suites/ad/50_ad_spec.rb
- spec/acceptance/suites/default/10_sssd_conf_spec.rb
- spec/acceptance/suites/ldap/10_setup_clients_spec.rb
- spec/acceptance/suites/ldap/templates/server_hieradata_tls.yaml.erb
- spec/classes/config_spec.rb
- spec/defines/provider/files_spec.rb
- spec/defines/provider/local_spec.rb
- templates/provider/local.erb
- Ensure that EL6/7+ use the 'files' or 'local' provider as is appropriate for
their platform
- Migrate the documentation to focus on the 'files' provider since 'local' is
not recommended to be used any longer
- Fixed the core acceptance tests
SIMP-7240 #close
> [SIMP-7240] Deprecate the 'local' provider on EL7+

- .gitlab-ci.yml
- .travis.yml
- Gemfile
This patch updates the puppet and ruby versions in the Gitlab CI
pipeline to reflect the latest PE LTS releases.  Most notably, it adds
specific tests for PE2019.8 LTS.
SIMP-7942 #close
[SIMP-7848] #comment Add PE2019.8 to GL CI in pupmod-simp-sssd
[SIMP-7855] #comment Update GL CI to PE2018.1.15 in pupmod-simp-sssd
[SIMP-7848]: https://simp-project.atlassian.net/browse/SIMP-7848
[SIMP-7855]: https://simp-project.atlassian.net/browse/SIMP-7855
> (SIMP-7848) Add PE2019.8 to pupmod-simp-sssd GL pipeline

- .github/workflows/pr_glci.yml
- .github/workflows/pr_glci_manual.yml
- .github/workflows/pr_tests.yml
- .gitlab-ci.yml
This patch updates the standardized GitHub Actions that trigger GLCI
pipelines:
- Still preemptively cancels existing GLCI pipelines for the same
branch, EXCEPT when a pipeline is for the same commit hashref.
- Refactored common GLCI logic into new composite run steps actions:
- [github-action-gitlab-ci-pipeline-trigger@v1][0]
- [github-action-gitlab-ci-syntax-check@v1][1]
This patch also enforces the standardized asset baseline using
simp/puppetsync, and may apply other updates to ensure conformity.
CI: SKIP MATRIX
[SIMP-9348] #close
[SIMP-9266] #comment Standardized GHA + assets in pupmod-simp-sssd
[SIMP-9279] #comment `.fixtures.yml` triggers GLCI acc for pupmod-simp-sssd
[0]: https://github.com/simp/github-action-gitlab-ci-pipeline-trigger
[1]: …
> (SIMP-9266) Improve GHA GCLI trigger in pupmod-simp-sssd

- CHANGELOG
- manifests/config/ipa_domain.pp
- spec/classes/config/ipa_domain_spec.rb
- spec/spec_helper.rb
- Ensure that systems bound to FreeIPA, but not connected do not cause
compilation issues.
> (SIMP-MAINT) IPA edge case fix

- spec/acceptance/suites/ad/nodesets/default.yml
- spec/acceptance/suites/ad/nodesets/oel.yml
This patch updates the Beaker nodesets' Windows boxes, replacing the
(currently 403) opentable/ boxes with boxes from devopsgroup-io/.
[SIMP-9605] #close
[SIMP-9603] #comment upgraded simp/sssd to devopsgroup-io box
[SIMP-9605]: https://simp-project.atlassian.net/browse/SIMP-9605
[SIMP-9603]: https://simp-project.atlassian.net/browse/SIMP-9603
> (SIMP-9603) Switch Windows SUT to devopsgroup-io/

- CHANGELOG
- manifests/service/sudo.pp
- metadata.json
- spec/acceptance/suites/default/10_sssd_conf_spec.rb
The sssd-sudo.socket service needed to be enabled, but not actively managed
since the sssd service itself would do that.
[SIMP-9720] #comment fix sssd issue
[SIMP-9720]: https://simp-project.atlassian.net/browse/SIMP-9720
> (SIMP-9720) Fix sssd-sudo.socket service

- CHANGELOG
- manifests/init.pp
- spec/acceptance/suites/default/00_default_spec.rb
- spec/classes/config_spec.rb
- sssd fails to start if it has no sssd domains configured.
This fix enables the implicit_files_domain by default.
SIMP-9778 #close
> (SIMP-9778) No domains cause failure

- spec/acceptance/nodesets/default.yml
- spec/acceptance/suites/ad/nodesets/default.yml
- spec/acceptance/suites/ds389/nodesets/default.yml
- spec/acceptance/suites/ldap/nodesets/default.yml
- spec/acceptance/suites/ldap/nodesets/oel.yml
- update the EL8 nodes in the acceptance tests
to run with generic/centos8 to make sure they using
CentOS 8.4
- update oel7 box to generic from onyxpoint in nodesets
- change repos in nodeset from packagecloud to simp-project
SIMP-10204 #comment update sssd
SIMP-10246 #close
> (SIMP-10204) Ensure testing with CentOS 8.4

- CHANGELOG
- REFERENCE.md
- manifests/service/sudo.pp
- metadata.json
- spec/acceptance/suites/ds389/10_setup_clients_spec.rb
- spec/acceptance/suites/ds389/nodesets/default.yml
- spec/acceptance/suites/ds389/nodesets/oel.yml
- spec/classes/service/sudo_spec.rb
- Add an override for sssd-sudo.service to start it as root:root. This aligns
with how sssd itself would start the service and the daemon cannot access
/var/lib/sss/db/config.ldb otherwise.
SIMP-10414 #close
> (SIMP-10414) Fix sssd-sudo service permissions

- CHANGELOG
- manifests/install.pp
- metadata.json
This is for compatibility with debian systems where sssd-client package does not exists.
Tested on Ubuntu 20.04 and other code seems to work fine.
> Add option to not install client tools

- .fixtures.yml
- .gitignore
- CHANGELOG
- manifests/service/sudo.pp
- metadata.json
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/oel.yml
- spec/acceptance/suites/ad/nodesets/default.yml
- spec/acceptance/suites/ad/nodesets/oel.yml
- spec/acceptance/suites/default/00_default_spec.rb
- spec/acceptance/suites/ds389/nodesets/default.yml
- spec/acceptance/suites/ds389/nodesets/oel.yml
- spec/acceptance/suites/ldap/nodesets/default.yml
- spec/acceptance/suites/ldap/nodesets/oel.yml
- spec/classes/service/sudo_spec.rb
- spec/spec_helper_acceptance.rb
This patch updates from camptocamp/systemd 2.x to puppet/systemd 3.x
This bump is driven by simp/simp-core#829
> Update deps to use puppet/systemd

- CHANGELOG
- REFERENCE.md
- manifests/provider/ldap.pp
- metadata.json
Some customers using AD integration use the ldap provider for some of
its unique parameters but do not include `ldap_uri` because it causes
issues for them.  This patch makes this configuration possible by making
`ldap_uri` an optional parameter.
> Make `ldap_uri` parameter optional

- .github/workflows/pr_tests.yml
- .gitlab-ci.yml
- Gemfile
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/oel.yml
- spec/acceptance/suites/ad/nodesets/default.yml
- spec/acceptance/suites/ad/nodesets/oel.yml
- spec/acceptance/suites/ds389/nodesets/default.yml
- spec/acceptance/suites/ds389/nodesets/oel.yml
- spec/acceptance/suites/ldap/nodesets/default.yml
- spec/acceptance/suites/ldap/nodesets/oel.yml
This patch moves puppet 6 refs to 7, puppet 7 refs to 8. Then we manually
update all spec nodesets to point to sicura oel boxes and comment out all 
pup8 tests.
The patch enforces a standardized asset baseline using simp/puppetsync,
and may also apply other updates to ensure conformity.
> Removes puppet 6 from .gitlab-ci.yml

- CHANGELOG
- REFERENCE.md
- manifests/domain.pp
- metadata.json
- templates/domain.erb
Hi,
just adding an simple option (ldap_user_search_filter) to the domain part. 
This option allows for example to filter out which users will be visible when running for example ```getent passwd```
br
> Add domain option ldap_user_search_filter

- CHANGELOG
- REFERENCE.md
- manifests/domain.pp
- metadata.json
> Add "ad" option to autofs_provider list
